services:
  my-nginx:
    image: nginx:stable-alpine
    container_name: nginx-reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # 將本地端的 nginx.conf 掛載到容器內的 /etc/nginx/nginx.conf
    ports:
      - "8080:80" # 將本地端的 8080 埠對應到容器內的 80 埠

  my-springboot-app:
    image: springboot-fileupload:v1
    container_name: springboot-fileupload
    volumes:
      - /Users/roger/Desktop/temp/:/app/uploaded_files/