@contextPath=/FileUploader


###
GET http://localhost:8080/{{contextPath}}/hello/hola

<> 2025-01-20T001854.200.txt


###
POST http://localhost:8080/{{contextPath}}/uploadBase64Image
Content-Type: application/json

< ../http-test-data/json-payload.json